footer:
-  heading: Europe
   links: 
    - text: Lorem Ipsum
      url: #
    - text: Lorem Ipsum
      url: #
    - text: Lorem Ipsum
      url: #
-  heading: Europe
   links: 
    - text: Lorem Ipsum
      url: #
    - text: Lorem Ipsum
      url: #
    - text: Lorem Ipsum
      url: #
-  heading: Europe
   links: 
    - text: Lorem Ipsum
      url: #
    - text: Lorem Ipsum
      url: #
    - text: Lorem Ipsum
      url: #

